# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=0)),
                ('isFast', models.BooleanField(default=False)),
                ('defect', models.BooleanField(default=False)),
                ('hasOwner', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0)),
                ('latitude', models.CharField(default=0, max_length=255)),
                ('longitude', models.CharField(default=0, max_length=255)),
                ('country', models.CharField(default=0, max_length=255)),
                ('city', models.CharField(default=0, max_length=255)),
                ('area', models.CharField(default=0, max_length=255)),
                ('neighborhood', models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlugType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='chargingspot',
            name='plugType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChargingAppointment.PlugType'),
        ),
    ]
