# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChargingAppointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('reservationDate', models.DateTimeField()),
                ('chargingStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChargingAppointment.ChargingSpot')),
            ],
        ),
    ]
