# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChargingAppointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingspot',
            name='defect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chargingspot',
            name='hasOwner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chargingspot',
            name='isFast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chargingspot',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='chargingspot',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
