# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChargingAppointment', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='userReservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
