# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 10:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChargingAppointment', '0003_appointment_userreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStationRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('chargingStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChargingAppointment.ChargingSpot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
