# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChargingAppointment', '0003_plugtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingspot',
            name='plugType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ChargingAppointment.PlugType'),
            preserve_default=False,
        ),
    ]
