# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChargingAppointment', '0004_chargingspot_plugtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingspot',
            name='area',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='chargingspot',
            name='city',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='chargingspot',
            name='country',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='chargingspot',
            name='latitude',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='chargingspot',
            name='longitude',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='chargingspot',
            name='neighborhood',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
