# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChargingAppointment', '0005_chargingstationrate_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstationrate',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
