# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChargingAppointment', '0006_chargingstationrate_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingspot',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
